"use client";

import { useRouter } from "next/navigation";
import { useState } from "react";

export function HomebrewImageUploader({ homebrewId }: { homebrewId: string }) {
  const router = useRouter();
  const [file, setFile] = useState<File | null>(null);
  const [imagePrompt, setImagePrompt] = useState("");
  const [imageAltText, setImageAltText] = useState("");
  const [generatedByAi, setGeneratedByAi] = useState(false);
  const [message, setMessage] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  async function upload(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();
    if (!file) {
      setMessage("Choose an image first.");
      return;
    }

    setLoading(true);
    setMessage(null);
    const formData = new FormData();
    formData.set("file", file);
    formData.set("imagePrompt", imagePrompt);
    formData.set("imageAltText", imageAltText);
    formData.set("generatedByAi", String(generatedByAi));
    const response = await fetch(`/api/homebrew/${homebrewId}/image`, { method: "POST", body: formData });
    const body = (await response.json().catch(() => null)) as { error?: string } | null;
    setLoading(false);
    if (!response.ok) {
      setMessage(body?.error || "Could not upload image.");
      return;
    }

    setMessage("Image uploaded.");
    setFile(null);
    router.refresh();
  }

  return (
    <form className="mt-4 grid gap-2 rounded-md border border-white/10 bg-black/20 p-3" onSubmit={upload}>
      <input className="text-sm text-zinc-300" type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={(event) => setFile(event.target.files?.[0] ?? null)} />
      <input className="rounded-md border border-white/10 bg-black/30 px-3 py-2 text-sm text-white" value={imageAltText} onChange={(event) => setImageAltText(event.target.value)} placeholder="Image alt text" />
      <textarea className="min-h-16 rounded-md border border-white/10 bg-black/30 p-2 text-sm text-white" value={imagePrompt} onChange={(event) => setImagePrompt(event.target.value)} placeholder="Image prompt or source note" />
      <label className="flex items-center gap-2 text-sm text-zinc-300">
        <input type="checkbox" checked={generatedByAi} onChange={(event) => setGeneratedByAi(event.target.checked)} />
        Generated by AI
      </label>
      <button className="rounded-md bg-mana px-3 py-2 text-sm font-semibold text-void disabled:opacity-60" disabled={loading} type="submit">
        {loading ? "Uploading..." : "Upload image"}
      </button>
      {message ? <p className="text-sm text-mana">{message}</p> : null}
    </form>
  );
}
